Modules/ResellersModule/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'auth:admin', 'prefix' => 'admin-panel', 'name' => ''], function () {

    Route::post('resellers/assign-servers', 'ResellersController@assignServerToReseller')->name('resellers.assign-server');

    Route::delete('resellers/delete/server/{id}', 'ResellersController@deleteResellerServer')->name('resellers.deleteServer');
    Route::get('resellers/assign-to-user/{id}/reseller_id/{reseller_id}', 'ResellersController@assignToUser')->name('reseller.assign_to_user');
    Route::post('resellers/assign-to-user', 'ResellersController@assignedToUser')->name('resellers.assignedToUser');

    Route::post('resellers/change/approval', 'ResellersController@changeApproval')->name('resellers.changeApproval');

    Route::resource('resellers', 'ResellersController');

});

Modules/ResellersModule/Entities/Reseller.php
<?php

namespace Modules\ResellersModule\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\UserModule\Entities\User;

class Reseller extends Model
{
    protected $guarded = [];

    public function servers()
    {
        return $this->hasMany(ResellerServer::class)->where('reseller_id', $this->id);

    }//end function

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');

    }//end function

}

Modules/ResellersModule/Http/Controllers/ResellersController.php
<?php

namespace Modules\ResellersModule\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;
use Modules\AreaModule\Entities\Country;
use Modules\ResellersModule\Entities\Reseller;
use Modules\ResellersModule\Entities\ResellerServer;
use Modules\ServerModule\Entities\Server;
use Modules\UserModule\Entities\User;
use Modules\UserModule\Entities\UserServer;

class ResellersController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function __construct()
    {
        $this->middleware('auth:admin');

    }//end function

    public function index()
    {


        $user_servers = UserServer::first();
        $now = Carbon::now();


        $resellers = User::reseller()->with('resellers')->get();


        return view('resellersmodule::resellers.index', compact('resellers'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $countries = Country::all();

        return view('resellersmodule::resellers.create', compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {

        $validator = \Illuminate\Support\Facades\Validator::make($request->all(), [

            'email' => [Rule::unique('users', 'email'), 'required'],
            'name' => 'required',
            'password' => 'required',
        ]);
        if ($validator->fails()) {
            return redirect()->back()->with('errors', $validator->errors());
        }
        $data = $request->except(['_token', 'password']);
        if ($request->password) {
            $password = Hash::make($request->password);
            $data['password'] = $password;
        }
        $user = new \Modules\UserModule\Entities\User();
        $user->name = $data['name'];
        $user->email = $data['email'];
        $user->password = $data['password'];
        $user->type = 'reseller';
        $user->country_id = $data['country_id'];
        $user->save();
        $data['user_id'] = $user->id;
        $reseller = $user->resellers()->create(['user_id' => $user->id]);

        return redirect()->route('resellers.index')->with('success', 'data stored');
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show($id)
    {
        $servers = Server::with('servers')->where('is_booked', 0)->get();
        $reseller = Reseller::with('user')->where('user_id', $id)->first();


        return view('resellersmodule::resellers.show', compact('servers', 'reseller'));
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit($id)
    {
        $countries = Country::all();

        $reseller = User::with('resellers')->find($id);
        return view('resellersmodule::resellers.edit', compact('reseller', 'countries'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @return Response
     */
    public function update($id, Request $request)
    {

        $data = $request->except('_token', '_method');


        $user = User::with('resellers')->find($id);
        $validator = \Illuminate\Support\Facades\Validator::make($request->all(), [

            'email' => [Rule::unique('users', 'email')->ignore($user->email, 'email'), 'required'],
            'name' => 'required',

        ]);
        if ($validator->fails()) {
            return redirect()->back()->with('errors', $validator->errors());
        }

        if ($request->has('password') && $request->password != null) {
            $user->update(['password' => Hash::make($request->password)]);
        }
        $user_info = $user->update([
            'name' => $data['name'],
            'email' => $data['email'],
            'country_id' => $data['country_id'],

        ]);


        return redirect()->route('resellers.index')->with('updated', 'data updated');


    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy($id)
    {
        $reseller = Reseller::with('user')->where('user_id', $id)->first();
        $reseller_servers = ResellerServer::where('reseller_id', $reseller->id)->get();


        if ($reseller_servers) {
            foreach ($reseller_servers as $reseller_server) {
                $server = Server::where('id', $reseller_server->server_id)->first();
                $server->update(['is_booked' => 0]);
                $reseller_server->delete();
            }

        }


        $reseller->user()->delete();
        $reseller->delete();
        return redirect()->route('resellers.index')->with('deleted', 'data deleted');

    }

    public function assignServerToReseller(Request $request)
    {


        $reseller_id = Reseller::where('id', $request->reseller_id)->first()->id;

        $server_from = Server::where('id', $request->from)->first();

        $server_to = Server::where('id', $request->to)->first();


        $servers = Server::where('is_booked', 0)->count();


        if ($servers > 0 && $server_from != null && $server_to != null) {
            for ($server_from->id; $server_from->id <= $server_to->id; $server_from->id++) {

                $reseller_server = ResellerServer::where('server_id', $server_from->id)->first();


                if ($reseller_server) {

                    return redirect()->back()->with('error', 'Server Number ' . $reseller_server->server_id . ' Is Already Booked');
                }


                ResellerServer::create(
                    [
                        'reseller_id' => $reseller_id,
                        'server_id' => $server_from->id,
                    ]
                );


                Server::where('id', $server_from->id)->update(['is_booked' => 1]);

            }
            return redirect()->route('resellers.index')->with('success', 'data stored');
        } else {
            return redirect()->back()->with('error', 'Not Available Server');
        }


    }//end function

    public function deleteResellerServer($server_id)
    {

        $server = ResellerServer::where('server_id', $server_id)->first();
        Server::where('id', $server_id)->first()->update(['is_booked' => 0]);

        $user_servers = UserServer::where('server_id', $server_id)->first();
        $server->delete();
        if ($user_servers) {

            $user_servers->delete();
        }
        return redirect()->back();

    }//end function

    public function assignToUser($server_id, $reseller_id)

    {

        $server = ResellerServer::where('server_id', $server_id)->first();
        $users = User::where('type', 'user')->get();
        $userServers = UserServer::get();


        return view('resellersmodule::resellers.assign_to_user', compact('server_id', 'reseller_id', 'users', 'userServers', 'server'));

    }//end function

    public function assignedToUser(Request $request)
    {


        $user_id = $request->user_id;
        $server_id = $request->server_id;
        $reseller_id = $request->reseller_id;
        $expiry_date = $request->expiry_date;
        $note = $request->note;

        $userServers = UserServer::where('server_id', $server_id)->first();
        if ($userServers != null) {

            return redirect()->back()->with('error', 'server is assigned before');
        }
        UserServer::create([
            'user_id' => $user_id,
            'server_id' => $server_id,
            'reseller_id' => $reseller_id,
            'expiry_date' => $expiry_date,

        ]);
        Server::where('id', $server_id)->update(['notes' => $note]);
        ResellerServer::where('server_id', $server_id)->update(['is_booked' => 1]);
        return redirect()->back()->with('success', 'data stored');

//        $user_id = $request->user_id;
//
//        $server_from = Server::where('id', $request->from)->first();
//        $server_to = Server::where('id', $request->to)->first();
//        $servers = ResellerServer::where('is_booked', 0)->count();
//
//        if ($servers > 0 && $server_from != null && $server_to != null) {
//            for ($server_from->id; $server_from->id <= $server_to->id; $server_from->id++) {
//
//                $userServer = UserServer::where('server_id', $server_from->id)->first();
//
//                if ($userServer) {
//
//                    return redirect()->back()->with('error', 'Server Number ' . $userServer->id . ' Is Already Booked');
//                }
//
//
//                UserServer::create(
//                    [
//                        'user_id' => $user_id,
//                        'server_id' => $server_from->id,
//                    ]
//                );
//                ResellerServer::where('server_id', $server_from->id)->update(['is_booked' => 1]);
//
//            }
//            return redirect()->back()->with('success', 'data stored');
//        } else {
//            return redirect()->back()->with('error', 'Not Available Server');
//        }

    }//end function

    public function changeApproval(Request $request)
    {
        $reseller_id = $request->reseller_id;
        $approval = $request->approval;

        $reseller = User::find($reseller_id);

        if ($approval == 1) {
            $reseller->update([
                'approval' => 0,
            ]);

        } elseif ($approval == 0) {

            $reseller->update(['approval' => 1]);
        }


        return redirect()->back();
    }//end function


}

Modules/ResellersModule/Resources/views/resellers/assign_to_user.blade.php
@extends('commonmodule::layouts.master')

@section('title')
    Assign servers   to Users
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('content-header')
    <section class="content-header">
        <h1>
            Assign servers to Users
        </h1>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">

                            {{--End Foreach--}}
                        </h3>
                        {{-- Add New--}}

                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        @if(session('error'))

                            <div class="alert alert-danger text-center">
                                {{session('error')}}
                            </div>
                        @endif
                        <table id="adminsTable" class="table table-bordered table-hover text-center">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>UserName</th>

                                <th>Assigning</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($users as $index => $user)
                                <tr>
                                    <td> {{$index+1}} </td>


                                    <td><a href="{{route('users.show',$user->id)}}">{{$user->name}}</a></td>


                                    <td>

                                        <form action="{{route('resellers.assignedToUser')}}" method="post" id="form_">
                                            @csrf
                                            <input type="hidden" value="{{$user->id}}" name="user_id">
                                            <input type="hidden" value="{{$server->server_id}}" name="server_id">
                                            <input type="hidden" value="{{$reseller_id}}" name="reseller_id">
                                            {{--                                            <label for="">from :</label>--}}
                                            {{--                                            <input type="number" name="from" id="from">--}}

                                            {{--                                            <label for="">To :</label>--}}
                                            {{--                                            <input type="number" name="to" id="to">--}}


                                            <input type="hidden" id="expiry_date" name="expiry_date">
                                            <input type="hidden" id="note" name="note">
                                            <button title="Assign" id="assign_form" data-toggle="modal" type="submit" data-target="#exampleModal" class="btn btn-success assign_form "><i class="fa fa-plane">Assign</i></button>


                                        </form>


                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->

    {{--start modal--}}

    <!-- Button trigger modal -->


        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Expiry date</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="date" id="expiry_date_modal" name="expiry_date" class="form-control">
                        <br>
                        <label class="control-label" for="">Write Note</label>
                        <textarea class="textarea" name="note" id="note_modal" cols="75" rows="10"></textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="save_form">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
        {{--end modal--}}
    </section>
@endsection

@section('javascript') {{-- sweet alert --}}

@include('commonmodule::includes.swal')

<!-- DataTables -->
<script src="{{asset('assets/admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
<script src="{{asset('assets/admin/bower_components/ckeditor/ckeditor.js')}}"></script>

<script>
    $(document).ready(function () {
        $('#adminsTable').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'info': true,
            'autoWidth': false,
            'language': {!! yajra_lang() !!}
        });
    })

</script>
<script>
    $(document).ready(function () {

        $('.assign_form').on('click', function (e) {
            e.preventDefault();
            $('#expiry_date_modal').on('change', function () {
                var _input = $('.assign_form').parent().find('#expiry_date');
                console.log(_input)
                _input.val($(this).val());
                console.log(_input.val())


            })

            $('#note_modal').on('change', function () {
                var _note = $('.assign_form').parent().find('#note');


                console.log($(this).val())
                _note.val($(this).val());


            })


        })
        $('#save_form').on('click', function () {
            $('#form_').submit();
        })

    })
</script>

@endsection

Modules/ResellersModule/Resources/views/resellers/create.blade.php
@extends('commonmodule::layouts.master')

@section('title')
    Resellers
@endsection

@section('css')

@endsection

@section('content-header')
    <section class="content-header">
        <h1>
            Resellers
        </h1>

    </section>
@endsection

@section('content')


    <section class="content">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title"> Resellers</h3>
            </div>


            @if ($errors->any())
                <div class="alert alert-danger ">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif

            <form class="form-horizontal" action="{{route('resellers.store')}}" method="POST">
                {{ csrf_field() }}

                <div class="box-body">
                    <div class="col-md-9">
                        <div class="nav-tabs-custom">


                            <div class="tab-content">


                                <div class="tab-pane active" id="">


                                    <div class="form-group">
                                        <label class="control-label col-sm-2">User Name :</label>
                                        <div class="col-sm-9">
                                            <input required type="text" autocomplete="off" value="" class="form-control" name="name">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Email :</label>
                                        <div class="col-sm-9">
                                            <input required type="email" autocomplete="off" value="" class="form-control" name="email">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Password :</label>
                                        <div class="col-sm-9">
                                            <input required type="password" autocomplete="off" value="" class="form-control" name="password">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Country :</label>
                                        <div class="col-sm-9">
                                            <select name="country_id" id="country_id" class="form-control">
                                                <option selected disabled value="">Select Country</option>
                                                @foreach($countries as $country)

                                                    <option value="{{$country->id}}">{{$country->name}}</option>
                                                @endforeach
                                                {{--End Foreach--}}
                                            </select>
                                        </div>
                                    </div>


                                </div>

                            </div>


                        </div>
                    </div>


                </div>
                <div class=" box-footer">
                    <button type="submit" class="btn btn-primary pull-right">
                        Save
                        <i class="fa fa-save"></i>
                    </button>
                </div>
            </form>
        </div>

    </section>
@endsection

@section('javascript')

    @include('commonmodule::includes.swal')

@endsection

Modules/ResellersModule/Resources/views/resellers/edit.blade.php
@extends('commonmodule::layouts.master')

@section('title')
    Resellers
@endsection

@section('css')

@endsection

@section('content-header')
    <section class="content-header">
        <h1>
            Resellers
        </h1>

    </section>
@endsection

@section('content')


    <section class="content">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title"> Resellers</h3>
            </div>


            @if ($errors->any())
                <div class="alert alert-danger ">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif

            <form class="form-horizontal" action="{{route('resellers.update',$reseller->id)}}" method="POST">
                @method('put')
                {{ csrf_field() }}

                <div class="box-body">
                    <div class="col-md-9">
                        <div class="nav-tabs-custom">


                            <div class="tab-content">


                                <div class="tab-pane active" id="">


                                    <div class="form-group">
                                        <label class="control-label col-sm-2">User Name :</label>
                                        <div class="col-sm-9">
                                            <input required type="text" autocomplete="off" value="{{$reseller->name}}" class="form-control" name="name">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Email :</label>
                                        <div class="col-sm-9">
                                            <input required type="email" autocomplete="off" value="{{$reseller->email}}" class="form-control" name="email">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Password :</label>
                                        <div class="col-sm-9">
                                            <input type="password" placeholder="it is blank if you dont change password" autocomplete="off" value="" class="form-control" name="password">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Country :</label>
                                        <div class="col-sm-9">

                                            <select name="country_id" id="country_id" class="form-control">
                                                <option selected disabled value="">Select Country</option>
                                                @foreach($countries as $country)

                                                    <option value="{{$country->id}}" {{$reseller->country_id == $country->id ?'selected':''}}>{{$country->name}}</option>
                                                @endforeach
                                                {{--End Foreach--}}
                                            </select>
                                        </div>
                                    </div>

                                </div>

                            </div>


                        </div>
                    </div>


                </div>
                <div class=" box-footer">
                    <button type="submit" class="btn btn-primary pull-right">
                        Save
                        <i class="fa fa-save"></i>
                    </button>
                </div>
            </form>
        </div>

    </section>
@endsection

@section('javascript')

    @include('commonmodule::includes.swal')

@endsection

Modules/ResellersModule/Resources/views/resellers/index.blade.php
@extends('commonmodule::layouts.master')

@section('title')
    Resellers
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('content-header')
    <section class="content-header">
        <h1> Resellers </h1>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Resellers</h3>
                        {{-- Add New--}}
                        <a href="{{url('admin-panel/resellers/create')}}" type="button" class="btn btn-success pull-right">
                            <i class="fa fa-plus" aria-hidden="true"></i> &nbsp; {{ trans('adminmodule::admin.add_new') }}
                        </a>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="resellersTable" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>UserName</th>
                                <th>Email</th>
                                <th>Approval</th>
                                <th>Operations</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($resellers as $index => $reseller)
                                <tr>
                                    <td> {{$index+1}} </td>


                                    <td> {{$reseller->name}} </td>
                                    <td> {{$reseller->email}} </td>
                                    <td>
                                        <form class="form_approval" action="{{route('resellers.changeApproval')}}" method="post">
                                            {!! csrf_field() !!}

                                            <input type="hidden" name="reseller_id" value="{{$reseller->id}}">
                                            <input type="hidden" name="approval" value="{{$reseller->approval}}">
                                            <input type="checkbox" name="approval" value="{{$reseller->approval}}" class="checkbox approval" {{($reseller->approval==1)?'checked':''}}>

                                        </form>
                                    </td>

                                    <td>

                                        <a title="Edit" href="{{url('admin-panel/resellers/' . $reseller->id . '/edit')}}" type="button" class="btn btn-primary">
                                            <i class="fa fa-pencil" aria-hidden="true"></i>
                                        </a>

                                        <a title="Edit" href="{{url('admin-panel/resellers/' . $reseller->id )}}" type="button" class="btn btn-warning">
                                            <i class="fa fa-server" aria-hidden="true"></i>
                                        </a>

                                        <form class="inline" action="{{url('admin-panel/resellers/' . $reseller->id)}}" method="POST">
                                            {{ method_field('DELETE') }} {!! csrf_field() !!}
                                            <button title="Delete" type="submit" onclick="return confirm('Are you sure, You want to delete Admin Data?')" type="button" class="btn btn-danger">
                                                <i class="fa fa-trash" aria-hidden="true"></i>
                                            </button>
                                        </form>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
@endsection

@section('javascript') {{-- sweet alert --}}

@include('commonmodule::includes.swal')

<!-- DataTables -->
<script src="{{asset('assets/admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>

<script>
    $(document).ready(function () {
        $('#adminsTable').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'info': true,
            'autoWidth': false,
            'language': {!! yajra_lang() !!}
        });


    })

</script>

<script>
    $('.approval').on('click', function () {
        var td = $(this).parent().parent().find('.form_approval').submit()


    })
</script>

@endsection