Modules/UserModule/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'auth:admin', 'prefix' => 'admin-panel', 'name' => ''], function () {

    Route::post('users/assign-servers', 'UsersController@assignServerToUser')->name('users.assign-server');

    Route::delete('users/delete/servers/{id}', 'UsersController@deleteUserServer')->name('users.deleteServer');

    Route::post('users/edit-expiry-date', 'UsersController@editExpiryDate')->name('users.expiryDate');

    Route::resource('users', 'UsersController');

});
Route::prefix('/front')->group(function () {


    Route::get('/login', 'UserLoginController@loginForm')->name('login');
    Route::get('/logout', 'UserLoginController@userLogout')->name('logout');


    Route::post('/do-login', 'UserLoginController@doUserLogin');
    Route::get('/register', 'UserLoginController@register');
    Route::post('/signup', 'UserLoginController@signup');

    Route::group(['middleware' => ['auth']], function () {
        Route::get('/profile/{id}', 'UserLoginController@profile');

        Route::post('/update-user/{id}', 'UserLoginController@update_username_mail');

        Route::post('/update-user-password/{id}', 'UserLoginController@update_password');
    });

});

Modules/UserModule/Entities/User.php
<?php

namespace Modules\UserModule\Entities;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Modules\ResellersModule\Entities\Reseller;
use Modules\ServerModule\Entities\UserFreeServer;

class User extends Authenticatable
{
    use Notifiable;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */


    protected $fillable = [
        'name', 'email', 'password', 'type', 'approval', 'country_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function servers()
    {
        return $this->hasMany(UserServer::class, 'user_id');

    }//end function

    public function resellers()
    {
        return $this->hasMany(Reseller::class, 'user_id');

    }//end function


    public function scopeReseller(Builder $builder)
    {
        return $builder->where('type', 'reseller');

    }//end function

    public function freeServer()
    {
        return $this->hasOne(UserFreeServer::class, 'user_id');

    }//end function

}

Modules/UserModule/Http/Controllers/UsersController.php
<?php

namespace Modules\UserModule\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;
use Modules\AreaModule\Entities\Country;
use Modules\ResellersModule\Entities\ResellerServer;
use Modules\ServerModule\Entities\Server;
use Modules\UserModule\Entities\User;
use Modules\UserModule\Entities\UserServer;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function __construct()
    {
        $this->middleware('auth:admin');

    }//end function

    public function index()
    {
        $users = DB::table('users')->where('type', 'user')->get();
        return view('usermodule::users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     * @return Response
     */
    public function create()
    {
        $countries = Country::with('translations')->get();
        return view('usermodule::users.create', compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {

        $validator = \Illuminate\Support\Facades\Validator::make($request->all(), [

            'email' => [Rule::unique('users', 'email'), 'required'],
            'name' => 'required',
            'password' => 'required',
        ]);
        if ($validator->fails()) {
            return redirect()->back()->with('errors', $validator->errors());
        }
        $data = $request->except(['_token', 'password']);
        if ($request->password) {
            $password = Hash::make($request->password);
            $data['password'] = $password;
        }

        $data['type'] = 'user';
        $user = User::create($data);

        return redirect()->route('users.index')->with('success', 'data stored');
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show($id)
    {

        $servers = Server::with('servers')->where('is_booked', 0)->get();
        $user = User::with('servers')->find($id);


        return view('usermodule::users.show', compact('servers', 'user'));
    }

    /**
     * Show the form for editing the specified resource.
     * @return Response
     */
    public function edit($id)
    {
        $countries = Country::with('translations')->get();
        $user = DB::table('users')->where('id', $id)->first();
        return view('usermodule::users.edit', compact('user', 'countries'));
    }

    /**
     * Update the specified resource in storage.
     * @param Request $request
     * @return Response
     */
    public function update($id, Request $request)
    {

        $data = $request->except('_token', '_method', 'password');

        $user = User::find($id);
        $validator = \Illuminate\Support\Facades\Validator::make($request->all(), [

            'email' => [Rule::unique('users', 'email')->ignore($user->email, 'email'), 'required'],
            'name' => 'required',

        ]);
        if ($validator->fails()) {
            return redirect()->back()->with('errors', $validator->errors());
        }

        if ($request->password && $request->password != null) {


            $user->update(['password' => Hash::make($request->password)]);


        }

        $user->update($data);
        return redirect()->route('users.index')->with('updated', 'data updated');


    }

    /**
     * Remove the specified resource from storage.
     * @return Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user_servers = UserServer::where('user_id', $id)->get();

        if ($user_servers) {
            foreach ($user_servers as $user_server) {

                $user_server->delete();
            }

        }

        $user->delete();
        return redirect()->route('users.index')->with('deleted', 'data deleted');

    }

    public function assignServerToUser(Request $request)
    {

        $user_id = $request->user_id;
        $server_from = Server::where('id', $request->from)->first();
        $server_to = Server::where('id', $request->to)->first();


        $servers = Server::where('is_booked', 0)->count();

        if ($servers > 0 && $server_from != null && $server_to != null) {
            for ($server_from->id; $server_from->id <= $server_to->id; $server_from->id++) {

                $userServer = UserServer::find($server_from->server_id);
                if ($userServer) {

                    return redirect()->back()->with('error', 'Server Number ' . $userServer->id . ' Is Already Booked');
                }

                UserServer::create(
                    [
                        'user_id' => $user_id,
                        'server_id' => $server_from->id,
                    ]
                );
                Server::where('id', $server_from->server_id)->update(['is_booked' => 1]);

            }
            return redirect()->route('users.index')->with('success', 'data stored');
        } else {
            return redirect()->back()->with('error', 'Not Available Server');
        }


    }//end function

    public function deleteUserServer($server_id)
    {

        $server = UserServer::where('server_id', $server_id)->first();


        $reseller_servers = ResellerServer::where('server_id', $server_id)->first();
        if ($reseller_servers) {
            $reseller_servers->update(['is_booked' => 0]);
            Server::where('id', $server_id)->update(['notes' => '']);
        }
        $server->delete();

        return redirect()->back();

    }//end function


    public function editExpiryDate(Request $request)
    {
        $server = UserServer::find($request->server_id);
        $server->update(['expiry_date' => $request->expiry_date]);

        return \response()->json(['success' => 'expiry date is updated successfully'], 200);

    }//end function

}

Modules/UserModule/Resources/views/users/create.blade.php
@extends('commonmodule::layouts.master')

@section('title')
    Users
@endsection

@section('css')

@endsection

@section('content-header')
    <section class="content-header">
        <h1>
            Users
        </h1>

    </section>
@endsection

@section('content')


    <section class="content">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title"> Users</h3>
            </div>


            @if ($errors->any())
                <div class="alert alert-danger ">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif

            <form class="form-horizontal" action="{{route('users.store')}}" method="POST">
                {{ csrf_field() }}

                <div class="box-body">
                    <div class="col-md-9">
                        <div class="nav-tabs-custom">


                            <div class="tab-content">


                                <div class="tab-pane active" id="">


                                    <div class="form-group">
                                        <label class="control-label col-sm-2">User Name :</label>
                                        <div class="col-sm-9">
                                            <input required type="text" autocomplete="off" value="" class="form-control" name="name">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Email :</label>
                                        <div class="col-sm-9">
                                            <input required type="email" autocomplete="off" value="" class="form-control" name="email">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Country :</label>
                                        <div class="col-sm-9">
                                            <select name="country_id" id="country_id" class="form-control">
                                                <option selected disabled value="">Select Country</option>
                                                @foreach($countries as $country)

                                                    <option value="{{$country->id}}">{{$country->name}}</option>
                                                @endforeach
                                                {{--End Foreach--}}
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Password :</label>
                                        <div class="col-sm-9">
                                            <input required type="password" autocomplete="off" value="" class="form-control" name="password">
                                        </div>
                                    </div>


                                </div>

                            </div>


                        </div>
                    </div>


                </div>
                <div class=" box-footer">
                    <button type="submit" class="btn btn-primary pull-right">
                        Save
                        <i class="fa fa-save"></i>
                    </button>
                </div>
            </form>
        </div>

    </section>
@endsection

@section('javascript')

    @include('commonmodule::includes.swal')

@endsection

Modules/UserModule/Resources/views/users/edit.blade.php
@extends('commonmodule::layouts.master')

@section('title')
    Users
@endsection

@section('css')

@endsection

@section('content-header')
    <section class="content-header">
        <h1>
            Users
        </h1>

    </section>
@endsection

@section('content')


    <section class="content">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title"> Users</h3>
            </div>


            @if ($errors->any())
                <div class="alert alert-danger ">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif

            <form class="form-horizontal" action="{{route('users.update',$user->id)}}" method="POST">
                @method('put')
                {{ csrf_field() }}

                <div class="box-body">
                    <div class="col-md-9">
                        <div class="nav-tabs-custom">


                            <div class="tab-content">


                                <div class="tab-pane active" id="">


                                    <div class="form-group">
                                        <label class="control-label col-sm-2">User Name :</label>
                                        <div class="col-sm-9">
                                            <input required type="text" autocomplete="off" value="{{$user->name}}" class="form-control" name="name">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Email :</label>
                                        <div class="col-sm-9">
                                            <input required type="email" autocomplete="off" value="{{$user->email}}" class="form-control" name="email">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Country :</label>
                                        <div class="col-sm-9">

                                            <select name="country_id" id="country_id" class="form-control">
                                                <option selected disabled value="">Select Country</option>
                                                @foreach($countries as $country)

                                                    <option value="{{$country->id}}" {{$user->country_id == $country->id ?'selected':''}}>{{$country->name}}</option>
                                                @endforeach
                                                {{--End Foreach--}}
                                            </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-sm-2">Password :</label>
                                        <div class="col-sm-9">
                                            <input type="password" placeholder="it is blank if you dont change password" autocomplete="off" value="" class="form-control" name="password">
                                        </div>
                                    </div>


                                </div>

                            </div>


                        </div>
                    </div>


                </div>
                <div class=" box-footer">
                    <button type="submit" class="btn btn-primary pull-right">
                        Save
                        <i class="fa fa-save"></i>
                    </button>
                </div>
            </form>
        </div>

    </section>
@endsection

@section('javascript')

    @include('commonmodule::includes.swal')

@endsection

Modules/UserModule/Resources/views/users/index.blade.php
@extends('commonmodule::layouts.master')

@section('title')
    Users
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
@endsection

@section('content-header')
    <section class="content-header">
        <h1> Users </h1>
    </section>
@endsection

@section('content')
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title">Users</h3>
                        {{-- Add New--}}
                        <a href="{{url('admin-panel/users/create')}}" type="button" class="btn btn-success pull-right">
                            <i class="fa fa-plus" aria-hidden="true"></i> &nbsp; {{ trans('adminmodule::admin.add_new') }}
                        </a>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="adminsTable" class="table table-bordered table-hover">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>UserName</th>
                                <th>Email</th>
                                <th>Approval</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($users as $index => $user)
                                <tr>
                                    <td> {{$index+1}} </td>


                                    <td> {{$user->name}} </td>
                                    <td> {{$user->email}} </td>


                                    <td>

                                        <a title="Edit" href="{{url('admin-panel/users/' . $user->id . '/edit')}}" type="button" class="btn btn-primary">
                                            <i class="fa fa-pencil" aria-hidden="true"></i>
                                        </a>

                                        <a title="Edit" href="{{url('admin-panel/users/' . $user->id )}}" type="button" class="btn btn-warning">
                                            <i class="fa fa-server" aria-hidden="true"></i>
                                        </a>

                                        <form class="inline" action="{{url('admin-panel/users/' . $user->id)}}" method="POST">
                                            {{ method_field('DELETE') }} {!! csrf_field() !!}
                                            <button title="Delete" type="submit" onclick="return confirm('Are you sure, You want to delete Admin Data?')" type="button" class="btn btn-danger">
                                                <i class="fa fa-trash" aria-hidden="true"></i>
                                            </button>
                                        </form>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
@endsection

@section('javascript') {{-- sweet alert --}}

@include('commonmodule::includes.swal')

<!-- DataTables -->
<script src="{{asset('assets/admin/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('assets/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>

<script>
    $(document).ready(function () {
        $('#adminsTable').DataTable({
            'paging': true,
            'lengthChange': true,
            'searching': true,
            'ordering': true,
            'info': true,
            'autoWidth': false,
            'language': {!! yajra_lang() !!}
        });
    })

</script>
@endsection

Modules/UserModule/Resources/views/users/show.blade.php
@extends('commonmodule::layouts.master')

@section('title')
    Users
@endsection

@section('css')

@endsection

@section('content-header')
    <section class="content-header">
        <h1>
            {{\Illuminate\Support\Str::ucfirst($user->name) }}
        </h1>

    </section>
@endsection

@section('content')


    <section class="content">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title"> Assign Servers To {{\Illuminate\Support\Str::ucfirst($user->name) }}</h3><br><br>


            </div>


            @if ($errors->any())
                <div class="alert alert-danger ">
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </div>
            @endif

            @if(session('error'))

                <div class="alert alert-danger text-center">
                    {{session('error')}}
                </div>
            @endif
            {{--End If--}}


            {{--            <form class="form-horizontal" action="{{route('users.assign-server')}}" method="POST">--}}
            {{--                {{ csrf_field() }}--}}

            {{--                <input type="hidden" value="{{$user->id}}" name="user_id">--}}


            {{--                <div class="box-body">--}}
            {{--                    <div class="col-md-9">--}}
            {{--                        <div class="nav-tabs-custom">--}}


            {{--                            <div class="tab-content">--}}


            {{--                                <div class="tab-pane active" id="">--}}


            {{--                                    <div class="row ">--}}
            {{--                                        <div class="col-sm-8">--}}
            {{--                                            <div class="col-md-3">--}}
            {{--                                                <div class="form-group">--}}

            {{--                                                    <label for="" class="col-sm-1">From</label>--}}
            {{--                                                    <div>--}}
            {{--                                                        <div class="col-sm-12">--}}
            {{--                                                            <input required @if($servers->count() <=0) disabled @endif type="number" autocomplete="off" value="" class="form-control" name="from">--}}
            {{--                                                        </div>--}}
            {{--                                                    </div>--}}
            {{--                                                </div>--}}
            {{--                                            </div>--}}


            {{--                                            <div class="col-md-3">--}}
            {{--                                                <div class="form-group">--}}

            {{--                                                    <label for=" " class="col-sm-1">To</label>--}}
            {{--                                                    <div>--}}
            {{--                                                        <div class="col-sm-12">--}}
            {{--                                                            <input required @if($servers->count() <=0) disabled @endif type="number" autocomplete="off" class="form-control" name="to">--}}
            {{--                                                        </div>--}}
            {{--                                                    </div>--}}
            {{--                                                </div>--}}
            {{--                                            </div>--}}
            {{--                                        </div>--}}

            {{--                                    </div>--}}


            {{--                                </div>--}}

            {{--                            </div>--}}


            {{--                        </div>--}}
            {{--                    </div>--}}


            {{--                </div>--}}
            {{--                <div class=" box-footer">--}}
            {{--                    <button type="submit" class="btn btn-primary pull-right">--}}
            {{--                        Save--}}
            {{--                        <i class="fa fa-save"></i>--}}
            {{--                    </button>--}}
            {{--                </div>--}}
            {{--            </form>--}}
            <div class="box-body">
                <table id="adminsTable" class="table table-bordered table-hover">
                    <thead>
                    <tr>

                        <th>Server ID</th>
                        <th>Expiry Date</th>
                        <th>Operations</th>

                    </tr>
                    </thead>
                    <tbody>


                    @foreach ($user->servers as $index => $server)


                        <tr>

                            <td><a href="{{route('servers.edit',$server->server_id)}}">{{$server->server_id}}</a></td>
                            <td>
                                <input type="hidden" name="server_id" id="server_id" value="{{$server->id}}">
                                {{$server->expiry_date}}
                                <a id="edit_modal" class="edit_modal" style="margin-left: 5px;" href=""><i class="fa fa-edit"></i></a>
                            </td>


                            <td>

                                <a title="Edit" href="{{url('admin-panel/servers/' . $server->server_id . '/edit')}}" type="button" class="btn btn-primary">
                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                </a>

                                <form class="inline" action="{{route('users.deleteServer' , $server->server_id)}}" method="POST">
                                    {{ method_field('DELETE') }} {!! csrf_field() !!}
                                    <button title="Delete" type="submit" onclick="return confirm('Are you sure, You want to delete Admin Data?')" type="button" class="btn btn-danger">
                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                    </button>
                                </form>
                            </td>

                        </tr>
                    @endforeach

                    {{--End If--}}

                    </tbody>
                </table>
            </div>

        </div>

    {{--start modal--}}

    <!-- Button trigger modal -->


        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Expiry date</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="date" value="" id="expiry_date_modal" name="expiry_date" class="form-control">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="save_form">Save changes</button>
                    </div>
                </div>
            </div>
        </div>
        {{--end modal--}}

    </section>
@endsection

@section('javascript')

    @include('commonmodule::includes.swal')


    <script>
        $('.edit_modal').on('click', function (e) {

            server_id = $(this).parent().find('#server_id').val();

            e.preventDefault();
            $('#exampleModal').modal().show;

            $('#save_form').on('click', function () {
                var expiry_date = $('#expiry_date_modal').val();

                $.ajax({
                    'type': 'post',
                    'url': '{{route('users.expiryDate')}}',

                    data: {
                        '_token': '{{csrf_token()}}',
                        'server_id': server_id,
                        'expiry_date': expiry_date,
                    },
                    beforeSend: function () {

                    },
                    'statusCode': {

                        200: function (response) {
                            $('#exampleModal').modal().hide();
                            window.location.reload();

                        },
                        404: function (xhr) {
                            $.each(xhr.responseJSON.errors, function (key, value) {
                                $('#validation-errors').append('<div class="alert alert-danger">' + value + '</div');
                            });
                        }
                    }


                });
            })

        })

    </script>

@endsection